export const airports = [
    {
      name: 'John F. Kennedy International Airport',
      code: 'JFK',
      city: 'New York',
      country: 'United States',
      timezone: 'America/New_York',
    },
    {
      name: 'Los Angeles International Airport',
      code: 'LAX',
      city: 'Los Angeles',
      country: 'United States',
      timezone: 'America/Los_Angeles',
    },
    {
      name: 'O\'Hare International Airport',
      code: 'ORD',
      city: 'Chicago',
      country: 'United States',
      timezone: 'America/Chicago',
    },
    {
      name: 'Heathrow Airport',
      code: 'LHR',
      city: 'London',
      country: 'United Kingdom',
      timezone: 'Europe/London',
    },
    {
      name: 'Charles de Gaulle Airport',
      code: 'CDG',
      city: 'Paris',
      country: 'France',
      timezone: 'Europe/Paris',
    },
    {
      name: 'Frankfurt Airport',
      code: 'FRA',
      city: 'Frankfurt',
      country: 'Germany',
      timezone: 'Europe/Berlin',
    },
    {
      name: 'Dubai International Airport',
      code: 'DXB',
      city: 'Dubai',
      country: 'United Arab Emirates',
      timezone: 'Asia/Dubai',
    },
    {
      name: 'Singapore Changi Airport',
      code: 'SIN',
      city: 'Singapore',
      country: 'Singapore',
      timezone: 'Asia/Singapore',
    },
    {
      name: 'Tokyo Haneda Airport',
      code: 'HND',
      city: 'Tokyo',
      country: 'Japan',
      timezone: 'Asia/Tokyo',
    },
    {
      name: 'Sydney Airport',
      code: 'SYD',
      city: 'Sydney',
      country: 'Australia',
      timezone: 'Australia/Sydney',
    },
    {
      name: 'Hartsfield-Jackson Atlanta International Airport',
      code: 'ATL',
      city: 'Atlanta',
      country: 'United States',
      timezone: 'America/New_York',
    },
    {
      name: 'San Francisco International Airport',
      code: 'SFO',
      city: 'San Francisco',
      country: 'United States',
      timezone: 'America/Los_Angeles',
    },
    {
      name: 'Miami International Airport',
      code: 'MIA',
      city: 'Miami',
      country: 'United States',
      timezone: 'America/New_York',
    },
    {
      name: 'Amsterdam Airport Schiphol',
      code: 'AMS',
      city: 'Amsterdam',
      country: 'Netherlands',
      timezone: 'Europe/Amsterdam',
    },
    {
      name: 'Rome Fiumicino Airport',
      code: 'FCO',
      city: 'Rome',
      country: 'Italy',
      timezone: 'Europe/Rome',
    }
  ];